[package]
name = "dexlyn_swap"
version = "0.1.0"
upgrade_policy = "compatible"

[addresses]
dexlyn_swap = "0x819322ee14f234cb912daaf62d50ecdef1b5d4a7ae9622d3c00b0b970cb295a0"

# Admins
dao_admin = "0x9a4dd870a230557e9551a1eaab48c19c76f6b1c34fd465b8bcedb64dae626cb4"
emergency_admin = "0x9a4dd870a230557e9551a1eaab48c19c76f6b1c34fd465b8bcedb64dae626cb4"
fee_admin = "0x9a4dd870a230557e9551a1eaab48c19c76f6b1c34fd465b8bcedb64dae626cb4"

# Resource accounts: should be the same as @dexlyn_swap_lp in lp_coin
dexlyn_swap_pool_account = "0x1abb3af119e2854f770af9abdd1bc3bd4c607a2334d3302f429f58f3fbde1d18"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"
test_admin_2 = "0xde18e0bb33eedc4e88f1823a64879074d84269004616be095d6cc0591df5ffb1"

[dependencies.DexlynswapLP]
local = "./dexlyn_swap_lp/"

[dependencies.SupraFramework]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/supra-framework'
rev = 'dev'
