[package]
name = 'DexlynswapLP'
version = '0.1.0'
upgrade_policy = "compatible"

[addresses]
dexlyn_swap_lp = "0x1abb3af119e2854f770af9abdd1bc3bd4c607a2334d3302f429f58f3fbde1d18"

[dev-dependencies.MoveStdlib]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = "aptos-move/framework/move-stdlib"
rev = 'dev'
